# Generated by Django 5.0.7 on 2024-07-31 03:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_nlpquery"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="mime",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="uploaded_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
