# Generated by Django 5.0.7 on 2024-07-31 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_uploadedfile_mime_uploadedfile_uploaded_on"),
    ]

    operations = [
        migrations.RenameField(
            model_name="uploadedfile",
            old_name="mime",
            new_name="content_type",
        ),
    ]
