# Generated by Django 5.0.7 on 2024-07-31 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_rename_mime_uploadedfile_content_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="nlpquery",
            name="same_file",
            field=models.BooleanField(default=False),
        ),
    ]
